const $ = (id) => document.getElementById(id);
let latest = {};
let signalCatalog = [];

function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function valueOfSignal(name){const v=latest?.obd?.signals?.[name]?.value;if(v&&typeof v==='object'&&'value'in v)return v.value;return v??null}
function displayValue(name,suffix=''){const v=valueOfSignal(name);return v===null||v===undefined?'--':`${typeof v==='number'?Math.round(v*10)/10:v}${suffix}`}
function badge(id,ok,warn=false){const el=$(id);el.classList.toggle('ok',!!ok);el.classList.toggle('warn',!ok&&warn)}
function fmtUptime(s){if(!s)return'--';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return`${h}h ${m}m`}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function renderState(data){latest=data||{};const obd=data.obd||{},gps=data.gps||{},mqtt=data.mqtt||{},sys=data.system||{},vehicle=obd.vehicle||{},dtc=obd.dtc||{};
$('speed').textContent=displayValue('SPEED');$('rpm').textContent=displayValue('RPM');$('coolant').textContent=displayValue('COOLANT_TEMP',' °C');$('load').textContent=displayValue('ENGINE_LOAD',' %');$('throttle').textContent=displayValue('THROTTLE_POS',' %');$('fuel').textContent=displayValue('FUEL_LEVEL',' %');$('voltage').textContent=displayValue('CONTROL_MODULE_VOLTAGE',' V');$('dtc-count').textContent=dtc.storedCount??0;
$('vin').textContent=vehicle.VIN||'Not available';$('protocol').textContent=obd.protocolName||vehicle.protocolName||'--';$('transport').textContent=obd.transport||'--';$('gps-detail').textContent=gps.validFix?`${gps.latitude??'--'}, ${gps.longitude??'--'} · ${gps.satellites??'--'} sats`:gps.received?'Data, waiting for fix':'Waiting';
$('vehicle-subtitle').textContent=vehicle.VIN?`VIN ${vehicle.VIN}`:(obd.connected?'Vehicle connected':'Waiting for vehicle…');badge('badge-gps',gps.validFix,gps.received);badge('badge-obd',obd.connected,obd.connecting);badge('badge-mqtt',mqtt.connected,mqtt.enabled);
$('sys-cpu').textContent=sys.cpuPercent==null?'--':`${sys.cpuPercent}%`;$('sys-temp').textContent=sys.temperatureC==null?'--':`${sys.temperatureC} °C`;$('sys-ram').textContent=sys.memoryAvailableMb==null?'--':`${sys.memoryAvailableMb} MB`;$('sys-disk').textContent=sys.diskFreeGb==null?'--':`${sys.diskFreeGb} GB`;$('sys-host').textContent=sys.hostname||'--';$('sys-ip').textContent=sys.ipAddress||'--';$('sys-uptime').textContent=fmtUptime(sys.uptimeSeconds);$('sys-agent').textContent=data.agent||'--';renderDtc(dtc,obd.dtcEvents||[]);}

function renderDtc(dtc,events){renderDtcList('stored-dtcs',dtc.stored||[]);renderDtcList('current-dtcs',dtc.currentCycle||[]);renderDtcList('freeze-dtc',dtc.freezeFrameCode?[dtc.freezeFrameCode]:[]);const recent=[...events].reverse().slice(0,15);const el=$('dtc-events');el.innerHTML=recent.length?recent.map(e=>`<div class="dtc-item"><b>${escapeHtml(e.event)} ${escapeHtml(e.code||'')}</b><small>${escapeHtml(e.scope||'')} · ${escapeHtml(e.timestamp||'')}</small></div>`).join(''):'<div class="empty">No DTC events yet.</div>'}
function renderDtcList(id,items){const el=$(id);el.innerHTML=items.length?items.map(d=>`<div class="dtc-item"><b>${escapeHtml(d.code)}</b><small>${escapeHtml(d.description||'No description available')}</small></div>`).join(''):'<div class="empty">None</div>'}

async function getJson(url){const r=await fetch(url);const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||r.statusText);return j}
async function postJson(url,body={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||r.statusText);return j}

async function loadSignals(){try{const d=await getJson('/api/signals');signalCatalog=d.supported||[];renderSignals(d)}catch(e){toast(e.message)}}
function renderSignals(data){const q=$('signal-search').value.trim().toLowerCase();const core=new Set(data.core||[]),selected=new Set(data.selected||[]);const rows=signalCatalog.filter(s=>!q||`${s.name} ${s.description}`.toLowerCase().includes(q));$('signal-list').innerHTML=rows.length?rows.map(s=>{const isCore=core.has(s.name),isSelected=selected.has(s.name);return`<div class="list-row"><div class="meta"><b>${escapeHtml(s.name)} ${isCore?'<small>CORE</small>':''}</b><small>${escapeHtml(s.description||'')}</small></div>${isCore?'<span class="small">Always on</span>':`<button data-signal="${escapeHtml(s.name)}" data-selected="${isSelected}">${isSelected?'Remove':'Add'}</button>`}</div>`}).join(''):'<div class="empty">No matching signals.</div>';
$('signal-list').querySelectorAll('button[data-signal]').forEach(btn=>btn.onclick=async()=>{try{await postJson('/api/signals/select',{name:btn.dataset.signal,selected:btn.dataset.selected!=='true'});await loadSignals()}catch(e){toast(e.message)}})}

async function loadSetup(){try{const [ports,bt]=await Promise.all([getJson('/api/obd/ports'),getJson('/api/bluetooth/status')]);$('port-info').textContent=`Mode: ${ports.mode}\nSelected: ${ports.selected?.kind||'none'} ${ports.selected?.port||''}\nUSB: ${(ports.usb||[]).join(', ')||'none'}\nBluetooth serial: ${ports.bluetoothPort}`;document.querySelectorAll('.transport-button').forEach(b=>b.classList.toggle('active',b.dataset.transport===ports.mode));renderBluetooth(bt)}catch(e){toast(e.message)}}
function renderBluetooth(data){const c=data.controller||{};$('bluetooth-controller').textContent=c.available?`Controller: ${c.powered?'ON':'OFF'} · configured ELM: ${data.configuredElmMac||'none'}`:`Bluetooth unavailable: ${c.error||''}`;const list=data.devices||[];$('bluetooth-list').innerHTML=list.length?list.map(d=>`<div class="list-row"><div class="meta"><b>${escapeHtml(d.name||d.mac)}</b><small>${escapeHtml(d.mac)} · ${d.paired?'paired':'not paired'} · ${d.connected?'connected':'disconnected'}</small></div><div class="button-row">${d.paired?'':`<button data-action="pair" data-mac="${d.mac}">Pair</button>`}<button data-action="use" data-mac="${d.mac}">Use as ELM</button>${d.connected?`<button data-action="disconnect" data-mac="${d.mac}">Disconnect</button>`:''}${d.paired?`<button data-action="forget" data-mac="${d.mac}">Forget</button>`:''}</div></div>`).join(''):'<div class="empty">No Bluetooth devices discovered yet.</div>';
$('bluetooth-list').querySelectorAll('button').forEach(btn=>btn.onclick=async()=>{const mac=btn.dataset.mac,action=btn.dataset.action;try{if(action==='pair'){const pin=prompt('Bluetooth PIN if required (for many ELM327 adapters: 1234 or 0000). Leave blank if none.')||'';await postJson('/api/bluetooth/pair',{mac,pin})}else if(action==='use'){await postJson('/api/bluetooth/use-elm',{mac})}else if(action==='disconnect'){await postJson('/api/bluetooth/disconnect',{mac})}else if(action==='forget'){if(!confirm(`Forget ${mac}?`))return;await postJson('/api/bluetooth/forget',{mac})}await loadSetup();toast('Bluetooth action completed')}catch(e){toast(e.message)}})}

function initTabs(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`tab-${b.dataset.tab}`).classList.add('active');if(b.dataset.tab==='signals')loadSignals();if(b.dataset.tab==='setup')loadSetup()})}
function initActions(){$('signal-search').oninput=()=>loadSignals();$('refresh-dtc').onclick=async()=>{try{await postJson('/api/dtc/refresh');toast('DTC scan complete')}catch(e){toast(e.message)}};$('clear-dtc').onclick=async()=>{const typed=prompt('Engine must be OFF. Type CLEAR to clear diagnostic codes.');if(typed!=='CLEAR')return;try{await postJson('/api/dtc/clear',{confirm:'CLEAR_DTC_CONFIRMED'});toast('DTC clear command completed')}catch(e){toast(e.message)}};document.querySelectorAll('.transport-button').forEach(b=>b.onclick=async()=>{try{await postJson('/api/obd/transport',{transport:b.dataset.transport});await loadSetup();toast(`OBD transport set to ${b.dataset.transport}`)}catch(e){toast(e.message)}});$('reconnect-obd').onclick=async()=>{try{await postJson('/api/obd/reconnect');toast('OBD reconnect requested')}catch(e){toast(e.message)}};$('scan-bluetooth').onclick=async()=>{try{toast('Scanning Bluetooth…');const d=await postJson('/api/bluetooth/scan',{});renderBluetooth({controller:(await getJson('/api/bluetooth/status')).controller,devices:d.devices});toast('Bluetooth scan complete')}catch(e){toast(e.message)}}}

function connectWs(){const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${proto}://${location.host}/ws/telemetry`);ws.onmessage=e=>{try{renderState(JSON.parse(e.data))}catch{}};ws.onclose=()=>setTimeout(connectWs,1500);ws.onerror=()=>ws.close()}
initTabs();initActions();getJson('/api/state').then(renderState).catch(()=>{});connectWs();
