#!/usr/bin/env python3
"""Regenerate docs/CODE_REFERENCE.md from the tracked implementation files."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = {
    '.html': 'html',
    '.js': 'javascript',
    '.py': 'python',
    '.sh': 'bash',
    '.toml': 'toml',
    '.yml': 'yaml',
    '.yaml': 'yaml',
}


def implementation_files():
    paths = [ROOT / 'pyproject.toml']
    for folder in ('.github', 'config', 'scripts', 'src', 'systemd', 'tests'):
        paths.extend(path for path in (ROOT / folder).rglob('*') if path.is_file())
    return sorted(
        path
        for path in paths
        if '__pycache__' not in path.parts and path.suffix not in {'.pyc', '.pyo'}
    )


def main():
    output = [
        '# Complete Code Reference',
        '',
        'Generated by `python scripts/generate-code-reference.py`.',
        'Every implementation and configuration file is listed below with its current contents.',
        '',
    ]
    for path in implementation_files():
        relative = path.relative_to(ROOT).as_posix()
        language = LANGUAGES.get(path.suffix, 'text')
        output.extend(
            [
                f'## `{relative}`',
                '',
                f'```{language}',
                path.read_text(encoding='utf-8').rstrip(),
                '```',
                '',
            ]
        )
    (ROOT / 'docs' / 'CODE_REFERENCE.md').write_text('\n'.join(output), encoding='utf-8')


if __name__ == '__main__':
    main()
